UNIT UAFILIADOS;

INTERFACE

USES
  WINDOWS, MESSAGES, SYSUTILS, VARIANTS, CLASSES, GRAPHICS, CONTROLS, FORMS,
  DIALOGS, GRIDS, DBGRIDS, DBCTRLS, EXTCTRLS, DB, DBTABLES, StdCtrls,
  Buttons;

TYPE
  TFRMAFILIADOS = CLASS(TFORM)
    PANEL1: TPANEL;
    PANEL2: TPANEL;
    DBNAVIGATOR1: TDBNAVIGATOR;
    DBGRID1: TDBGRID;
    DTSAFILIADOS: TDATASOURCE;
    nombre: TLabel;
    edtnombre: TEdit;
    BitBtn1: TBitBtn;
    PROCEDURE FORMCREATE(SENDER: TOBJECT);
    PROCEDURE FORMCLOSE(SENDER: TOBJECT; VAR ACTION: TCLOSEACTION);
    PROCEDURE DBGRID1DBLCLICK(SENDER: TOBJECT);
    PROCEDURE AUTILIQUIDACIONES;
    PROCEDURE INCAPACIDADES;
    PROCEDURE INCAPACIDADES_TUTELA;
    PROCEDURE CORRECIONES;
    procedure FormActivate(Sender: TObject);
    procedure BitBtn1Click(Sender: TObject);
  PRIVATE
    { PRIVATE DECLARATIONS }
  PUBLIC
    { PUBLIC DECLARATIONS }
  END;

VAR
  FRMAFILIADOS: TFRMAFILIADOS;

IMPLEMENTATION

USES DTMODULO, UPLANILLAS, UINCAPACIDADES, UGLOBAL, Uplanillacorreciones,
  UincapacidadesTUTELA;

{$R *.DFM}

PROCEDURE TFRMAFILIADOS.FORMCREATE(SENDER: TOBJECT);
BEGIN
    DATAMODULE1.QRYAFILIADOS.CLOSE;
    DATAMODULE1.QRYAFILIADOS.SQL.CLEAR;
    DATAMODULE1.QRYAFILIADOS.SQL.ADD('SELECT  TIP_DOCUMENTO_EMP, NUM_DOCUMENTO_EMP,TIP_DOCUMENTO_AFI, NUM_DOCUMENTO_AFI,PRI_APELLIDO,SEG_APELLIDO,PRI_NOMBRE,SEG_NOMBRE,VAL_SUELDO_AFIL,FEC_INGRESO_UNI,FEC_EGRESO_UNI,AFILIADOS_EMPRESAS.COD_ESTADO,FEC_NACIMIENTO,COD_SEXO,T1.COD_MODALIDAD_TRA');
    DATAMODULE1.QRYAFILIADOS.SQL.ADD('FROM AFILIADOS_EMPRESAS,AFILIADOS T1');
    DATAMODULE1.QRYAFILIADOS.SQL.ADD('WHERE TIP_DOCUMENTO_AFI = TIP_DOCUMENTO AND NUM_DOCUMENTO_AFI = NUM_DOCUMENTO AND TIP_DOCUMENTO_EMP = :"NIT" AND NUM_DOCUMENTO_EMP = :"DOCUMENTO" AND AFILIADOS_EMPRESAS.COD_ESTADO = :"ESTADO" ORDER BY PRI_APELLIDO,SEG_APELLIDO,PRI_NOMBRE,SEG_NOMBRE');
    IF GLPROCESO = 'AUTOLIQUIDACIONES' THEN
    BEGIN
        DATAMODULE1.QRYAFILIADOS.Parameters[0].VALUE := TRIM(FRMPLANILLAS.CBTIPODOCEMPRESA.TEXT);
        DATAMODULE1.QRYAFILIADOS.Parameters[1].VALUE := TRIM(FRMPLANILLAS.EDNUMERO.TEXT);
        DATAMODULE1.QRYAFILIADOS.Parameters[2].VALUE := 'A';
    END
    ELSE IF GLPROCESO = 'INCAPACIDADES' THEN
    BEGIN
        DATAMODULE1.QRYAFILIADOS.Parameters[0].VALUE := TRIM(FRMINCAPACIDADES.CBTIPODOCEMPRESA.TEXT);
        DATAMODULE1.QRYAFILIADOS.Parameters[1].VALUE := TRIM(FRMINCAPACIDADES.EDTNUMDOCEMPRESA.TEXT);
        DATAMODULE1.QRYAFILIADOS.Parameters[2].VALUE := 'A';
        END
        ELSE IF GLPROCESO = 'INCAPACIDADES TUTELA' THEN
        BEGIN
        DATAMODULE1.QRYAFILIADOS.Parameters[0].VALUE := TRIM(FRMINCAPACIDADESTUTELA.CBTIPODOCEMPRESA.TEXT);
        DATAMODULE1.QRYAFILIADOS.Parameters[1].VALUE := TRIM(FRMINCAPACIDADESTUTELA.EDTNUMDOCEMPRESA.TEXT);
        DATAMODULE1.QRYAFILIADOS.Parameters[2].VALUE := 'A';
        END
        else IF GLPROCESO = 'CORRECIONES' THEN
    BEGIN
        DATAMODULE1.QRYAFILIADOS.Parameters[0].VALUE := TRIM(frmcorreciones.cbtipodocempresa.TEXT);
        DATAMODULE1.QRYAFILIADOS.Parameters[1].VALUE := TRIM(frmcorreciones.EDNUMERO.TEXT);
        DATAMODULE1.QRYAFILIADOS.Parameters[2].VALUE := 'A';
        END;
     DATAMODULE1.QRYAFILIADOS.OPEN;
    IF DATAMODULE1.QRYAFILIADOS.RECORDCOUNT = 0 THEN
      BEGIN
       SHOWMESSAGE('NO EXISTEN AFILIADOS  POR  ESTA  EMPRESA');
       END;
    END;

PROCEDURE TFRMAFILIADOS.FORMCLOSE(SENDER: TOBJECT;
  VAR ACTION: TCLOSEACTION);
BEGIN
ACTION:=CAFREE;
END;

PROCEDURE TFRMAFILIADOS.DBGRID1DBLCLICK(SENDER: TOBJECT);
BEGIN
IF GLPROCESO = 'AUTOLIQUIDACIONES' THEN
   BEGIN
   AUTILIQUIDACIONES;
   END
       ELSE IF GLPROCESO = 'INCAPACIDADES' THEN
       BEGIN
       INCAPACIDADES;
       END
       ELSE IF GLPROCESO = 'CORRECIONES' THEN
            BEGIN
            CORRECIONES;
            END
            ELSE IF GLPROCESO = 'INCAPACIDADES TUTELA' THEN
                  BEGIN
                  INCAPACIDADES_TUTELA;
                  END
       
END;
PROCEDURE TFRMAFILIADOS.AUTILIQUIDACIONES;
BEGIN
IF DATAMODULE1.QRYAFILIADOSTIP_DOCUMENTO_AFI.TEXT = 'CC' THEN
    BEGIN
    FRMPLANILLAS.CBTIPODOCAFILIADO.ITEMINDEX := 0;
    END
      ELSE IF DATAMODULE1.QRYAFILIADOSTIP_DOCUMENTO_AFI.TEXT = 'CE' THEN
              BEGIN
              FRMPLANILLAS.CBTIPODOCAFILIADO.ITEMINDEX := 1;
              END
              ELSE IF DATAMODULE1.QRYAFILIADOSTIP_DOCUMENTO_AFI.TEXT = 'TI' THEN
                   BEGIN
                   FRMPLANILLAS.CBTIPODOCAFILIADO.ITEMINDEX := 2;
                   END;

    FRMPLANILLAS.EDTNUMERODUCAFILIADO.TEXT := DATAMODULE1.QRYAFILIADOSNUM_DOCUMENTO_AFI.TEXT;
    FRMPLANILLAS.EDTNOMBREAFILIADO.TEXT := DATAMODULE1.QRYAFILIADOSPRI_APELLIDO.VALUE + ' ' + DATAMODULE1.QRYAFILIADOSSEG_APELLIDO.VALUE + ' ' + DATAMODULE1.QRYAFILIADOSPRI_NOMBRE.VALUE + ' ' + DATAMODULE1.QRYAFILIADOSSEG_NOMBRE.VALUE;
    FRMAFILIADOS.FREE;
    FRMPLANILLAS.EDTNUMERODUCAFILIADO.SETFOCUS;
END;

PROCEDURE TFRMAFILIADOS.INCAPACIDADES;
BEGIN
IF DATAMODULE1.QRYAFILIADOSTIP_DOCUMENTO_AFI.TEXT = 'CC' THEN
    BEGIN
    FRMINCAPACIDADES.CBTIPODOCAFILIADO.ITEMINDEX := 0;
    END
      ELSE IF DATAMODULE1.QRYAFILIADOSTIP_DOCUMENTO_AFI.TEXT = 'CE' THEN
              BEGIN
              FRMINCAPACIDADES.CBTIPODOCAFILIADO.ITEMINDEX := 1;
              END
              ELSE IF DATAMODULE1.QRYAFILIADOSTIP_DOCUMENTO_AFI.TEXT = 'TI' THEN
                   BEGIN
                   FRMINCAPACIDADES.CBTIPODOCAFILIADO.ITEMINDEX := 2;
                   END;


    FRMINCAPACIDADES.EDTNUMDOCAFILIADOIN.TEXT := DATAMODULE1.QRYAFILIADOSNUM_DOCUMENTO_AFI.TEXT;
    FRMINCAPACIDADES.EDTNOMBREAFILIADO.TEXT := DATAMODULE1.QRYAFILIADOSPRI_APELLIDO.VALUE + ' ' + DATAMODULE1.QRYAFILIADOSSEG_APELLIDO.VALUE + ' ' + DATAMODULE1.QRYAFILIADOSPRI_NOMBRE.VALUE + ' ' + DATAMODULE1.QRYAFILIADOSSEG_NOMBRE.VALUE;
    FRMAFILIADOS.FREE;
    FRMINCAPACIDADES.EDTNUMDOCAFILIADOIN.SetFocus;
END;

PROCEDURE TFRMAFILIADOS.INCAPACIDADES_TUTELA;
BEGIN
 IF DATAMODULE1.QRYAFILIADOSTIP_DOCUMENTO_AFI.TEXT = 'CC' THEN
    BEGIN
    FRMINCAPACIDADESTUTELA.CBTIPODOCAFILIADO.ITEMINDEX := 0;
    END
      ELSE IF DATAMODULE1.QRYAFILIADOSTIP_DOCUMENTO_AFI.TEXT = 'CE' THEN
              BEGIN
              FRMINCAPACIDADESTUTELA.CBTIPODOCAFILIADO.ITEMINDEX := 1;
              END
              ELSE IF DATAMODULE1.QRYAFILIADOSTIP_DOCUMENTO_AFI.TEXT = 'TI' THEN
                   BEGIN
                   FRMINCAPACIDADESTUTELA.CBTIPODOCAFILIADO.ITEMINDEX := 2;
                   END;

    FRMINCAPACIDADESTUTELA.EDTNUMDOCAFILIADOIN.TEXT := DATAMODULE1.QRYAFILIADOSNUM_DOCUMENTO_AFI.TEXT;
    FRMINCAPACIDADESTUTELA.EDTNOMBREAFILIADO.TEXT := DATAMODULE1.QRYAFILIADOSPRI_APELLIDO.VALUE + ' ' + DATAMODULE1.QRYAFILIADOSSEG_APELLIDO.VALUE + ' ' + DATAMODULE1.QRYAFILIADOSPRI_NOMBRE.VALUE + ' ' + DATAMODULE1.QRYAFILIADOSSEG_NOMBRE.VALUE;
    FRMAFILIADOS.FREE;
    FRMINCAPACIDADESTUTELA.EDTNUMDOCAFILIADOIN.SetFocus;
END;

procedure TFRMAFILIADOS.CORRECIONES;
begin
IF DATAMODULE1.QRYAFILIADOSTIP_DOCUMENTO_AFI.TEXT = 'CC' THEN
    BEGIN
    frmcorreciones.CBTIPODOCAFILIADO.ITEMINDEX := 0;
    END
      ELSE IF DATAMODULE1.QRYAFILIADOSTIP_DOCUMENTO_AFI.TEXT = 'CE' THEN
              BEGIN
              frmcorreciones.CBTIPODOCAFILIADO.ITEMINDEX := 1;
              END
              ELSE IF DATAMODULE1.QRYAFILIADOSTIP_DOCUMENTO_AFI.TEXT = 'TI' THEN
                   BEGIN
                   frmcorreciones.CBTIPODOCAFILIADO.ITEMINDEX := 2;
                   END;

    frmcorreciones.EDTNUMERODUCAFILIADO.TEXT := DATAMODULE1.QRYAFILIADOSNUM_DOCUMENTO_AFI.TEXT;
    frmcorreciones.EDTNOMBREAFILIADO.TEXT := DATAMODULE1.QRYAFILIADOSPRI_APELLIDO.VALUE + ' ' + DATAMODULE1.QRYAFILIADOSSEG_APELLIDO.VALUE + ' ' + DATAMODULE1.QRYAFILIADOSPRI_NOMBRE.VALUE + ' ' + DATAMODULE1.QRYAFILIADOSSEG_NOMBRE.VALUE;
    FRMAFILIADOS.FREE;
    frmcorreciones.EDTNUMERODUCAFILIADO.SETFOCUS;

end;

procedure TFRMAFILIADOS.FormActivate(Sender: TObject);
begin
top := 7;
end;

procedure TFRMAFILIADOS.BitBtn1Click(Sender: TObject);
begin

    DATAMODULE1.QRYAFILIADOS.CLOSE;
    DATAMODULE1.QRYAFILIADOS.SQL.CLEAR;
    DATAMODULE1.QRYAFILIADOS.SQL.ADD('SELECT  TIP_DOCUMENTO_EMP, NUM_DOCUMENTO_EMP,TIP_DOCUMENTO_AFI, NUM_DOCUMENTO_AFI,PRI_APELLIDO,SEG_APELLIDO,PRI_NOMBRE,SEG_NOMBRE,VAL_SUELDO_AFIL,FEC_INGRESO_UNI,FEC_EGRESO_UNI,AFILIADOS_EMPRESAS.COD_ESTADO,FEC_NACIMIENTO,COD_SEXO,T1.COD_MODALIDAD_TRA');
    DATAMODULE1.QRYAFILIADOS.SQL.ADD('FROM AFILIADOS_EMPRESAS,AFILIADOS T1');
    DATAMODULE1.QRYAFILIADOS.SQL.ADD('WHERE TIP_DOCUMENTO_AFI = TIP_DOCUMENTO AND NUM_DOCUMENTO_AFI = NUM_DOCUMENTO AND TIP_DOCUMENTO_EMP = :"NIT" AND NUM_DOCUMENTO_EMP = :"DOCUMENTO" AND AFILIADOS_EMPRESAS.COD_ESTADO = :"ESTADO" AND PRI_APELLIDO LIKE :"APELLIDO"');
    DATAMODULE1.QRYAFILIADOS.SQL.ADD('ORDER BY PRI_APELLIDO,SEG_APELLIDO,PRI_NOMBRE,SEG_NOMBRE');
    IF GLPROCESO = 'AUTOLIQUIDACIONES' THEN
    BEGIN
        DATAMODULE1.QRYAFILIADOS.Parameters[0].VALUE := FRMPLANILLAS.CBTIPODOCEMPRESA.TEXT;
        DATAMODULE1.QRYAFILIADOS.Parameters[1].VALUE := FRMPLANILLAS.EDNUMERO.TEXT;
        DATAMODULE1.QRYAFILIADOS.Parameters[2].VALUE := 'A';
        DATAMODULE1.QRYAFILIADOS.Parameters[3].VALUE := '%' + TRIM(EDTNOMBRE.Text) + '%';
    END
    ELSE IF GLPROCESO = 'INCAPACIDADES' THEN
    BEGIN
        DATAMODULE1.QRYAFILIADOS.Parameters[0].VALUE := TRIM(FRMINCAPACIDADES.CBTIPODOCEMPRESA.TEXT);
        DATAMODULE1.QRYAFILIADOS.Parameters[1].VALUE := TRIM(FRMINCAPACIDADES.EDTNUMDOCEMPRESA.TEXT);
        DATAMODULE1.QRYAFILIADOS.Parameters[2].VALUE := 'A';
        DATAMODULE1.QRYAFILIADOS.Parameters[3].VALUE := '%' + TRIM(EDTNOMBRE.Text) + '%';
        END
        ELSE IF GLPROCESO = 'INCAPACIDADES TUTELA' THEN
        BEGIN
        DATAMODULE1.QRYAFILIADOS.Parameters[0].VALUE := TRIM(FRMINCAPACIDADESTUTELA.CBTIPODOCEMPRESA.TEXT);
        DATAMODULE1.QRYAFILIADOS.Parameters[1].VALUE := TRIM(FRMINCAPACIDADESTUTELA.EDTNUMDOCEMPRESA.TEXT);
        DATAMODULE1.QRYAFILIADOS.Parameters[2].VALUE := 'A';
        DATAMODULE1.QRYAFILIADOS.Parameters[3].VALUE := '%' + TRIM(EDTNOMBRE.Text) + '%';
        END
        else IF GLPROCESO = 'CORRECIONES' THEN
    BEGIN
        DATAMODULE1.QRYAFILIADOS.Parameters[0].VALUE := TRIM(frmcorreciones.cbtipodocempresa.TEXT);
        DATAMODULE1.QRYAFILIADOS.Parameters[1].VALUE := TRIM(frmcorreciones.edtnumeroducafiliado.TEXT);
        DATAMODULE1.QRYAFILIADOS.Parameters[2].VALUE := 'A';
        DATAMODULE1.QRYAFILIADOS.Parameters[3].VALUE := '%' + TRIM(EDTNOMBRE.Text) + '%';
        END;
    DATAMODULE1.QRYAFILIADOS.OPEN;
    IF DATAMODULE1.QRYAFILIADOS.RECORDCOUNT = 0 THEN
    BEGIN
       SHOWMESSAGE('NO SE ENCUENTRA  EL AFILIADO  POR  ESTA  EMPRESA');
    END;
end;

END.

