UNIT UDIAGNOSTICOS;

INTERFACE


USES
  WINDOWS, MESSAGES, CLASSES, SYSUTILS, GRAPHICS, CONTROLS, STDCTRLS, FORMS,
  DIALOGS, DBCTRLS, DB, DBGRIDS, DBTABLES, GRIDS, EXTCTRLS;



TYPE
  TFRMDIAGNOSTICOS = CLASS(TFORM)
    DBGRID1: TDBGRID;
    DBNAVIGATOR: TDBNAVIGATOR;
    PANEL1: TPANEL;
    DATASOURCE1: TDATASOURCE;
    PANEL2: TPANEL;
    edtbuscar: TEdit;
    btnbuscar: TButton;
    Label1: TLabel;
    PROCEDURE FORMCREATE(SENDER: TOBJECT);
    PROCEDURE DBGRID1DBLCLICK(SENDER: TOBJECT);
    procedure FormActivate(Sender: TObject);
    procedure btnbuscarClick(Sender: TObject);
    procedure FormClose(Sender: TObject; var Action: TCloseAction);

  PRIVATE
    { PRIVATE DECLARATIONS }
  PUBLIC
    { PUBLIC DECLARATIONS }
  END;

VAR
  FRMDIAGNOSTICOS: TFRMDIAGNOSTICOS;
  PANTALLA:STRING;

  IMPLEMENTATION

USES UINCAPACIDADES, UGLOBAL, DTMODULO, UincapacidadesTUTELA;

{$R *.DFM}

PROCEDURE TFRMDIAGNOSTICOS.FORMCREATE(SENDER: TOBJECT);
BEGIN
 IF PANTALLA='Diagnósticos' THEN
 BEGIN
     IF FRMINCAPACIDADES.edtcoddiagnostico.Text<>'0' THEN
     BEGIN
        DATAMODULE1.QRYDIAGNOSTICOS.CLOSE;
        DATAMODULE1.QRYDIAGNOSTICOS.SQL.CLEAR;
        DATAMODULE1.QRYDIAGNOSTICOS.SQL.ADD('SELECT * FROM DIAGNOSTICOS WHERE ((RANGO_SEXO = :"SEXO") OR(RANGO_SEXO = :"SEXOF")) AND ((EDA_MININA <=:"EDAD") AND (EDA_MAXIMA >= :"EDAD"))');
        IF  FRMINCAPACIDADES.EDTSEXO.TEXT = 'M' THEN
         BEGIN
        DATAMODULE1.QRYDIAGNOSTICOS.Parameters[0].VALUE := '1';
        END
        ELSE IF  FRMINCAPACIDADES.EDTSEXO.TEXT = 'F' THEN
             BEGIN
             DATAMODULE1.QRYDIAGNOSTICOS.Parameters[0].VALUE := '2';
             END;
        DATAMODULE1.QRYDIAGNOSTICOS.Parameters[1].VALUE := '3';
        DATAMODULE1.QRYDIAGNOSTICOS.Parameters[2].VALUE := STRTOINT(FRMINCAPACIDADES.EDTEDAD.TEXT);
        DATAMODULE1.QRYDIAGNOSTICOS.Parameters[3].VALUE := STRTOINT(FRMINCAPACIDADES.EDTEDAD.TEXT);
        DATAMODULE1.QRYDIAGNOSTICOS.OPEN;
     END
     ELSE
     BEGIN
     SHOWMESSAGE('NO HAY DIAGNOSTICOS CON ESTE NOMBRE');
     FRMINCAPACIDADES.Edtnumero.SetFocus;
     END;
 END
  ELSE IF PANTALLA='Diagnósticos Tutela' THEN
  BEGIN
     IF FRMINCAPACIDADESTUTELA.edtcoddiagnostico.Text<>'0' THEN
     BEGIN
        DATAMODULE1.QRYDIAGNOSTICOS.CLOSE;
        DATAMODULE1.QRYDIAGNOSTICOS.SQL.CLEAR;
        DATAMODULE1.QRYDIAGNOSTICOS.SQL.ADD('SELECT * FROM DIAGNOSTICOS WHERE ((RANGO_SEXO = :"SEXO") OR(RANGO_SEXO = :"SEXOF")) AND ((EDA_MININA <=:"EDAD") AND (EDA_MAXIMA >= :"EDAD"))');
        IF  FRMINCAPACIDADESTUTELA.EDTSEXO.TEXT = 'M' THEN
         BEGIN
        DATAMODULE1.QRYDIAGNOSTICOS.Parameters[0].VALUE := '1';
        END
        ELSE IF  FRMINCAPACIDADESTUTELA.EDTSEXO.TEXT = 'F' THEN
             BEGIN
             DATAMODULE1.QRYDIAGNOSTICOS.Parameters[0].VALUE := '2';
             END;
        DATAMODULE1.QRYDIAGNOSTICOS.Parameters[1].VALUE := '3';
        DATAMODULE1.QRYDIAGNOSTICOS.Parameters[2].VALUE := STRTOINT(FRMINCAPACIDADESTUTELA.EDTEDAD.TEXT);
        DATAMODULE1.QRYDIAGNOSTICOS.Parameters[3].VALUE := STRTOINT(FRMINCAPACIDADESTUTELA.EDTEDAD.TEXT);
        DATAMODULE1.QRYDIAGNOSTICOS.OPEN;
     END
     ELSE
     BEGIN
     SHOWMESSAGE('NO HAY DIAGNOSTICOS CON ESTE NOMBRE');
     FRMINCAPACIDADESTUTELA.Edtnumero.SetFocus;
     END;
  END

END;

PROCEDURE TFRMDIAGNOSTICOS.DBGRID1DBLCLICK(SENDER: TOBJECT);
BEGIN
IF FRMDIAGNOSTICOS.Caption='Diagnósticos' THEN
   BEGIN
   FRMINCAPACIDADES.EDTCODDIAGNOSTICO.TEXT := DATAMODULE1.QRYDIAGNOSTICOSCOD_DIAGNOSTICO.TEXT;
   FRMINCAPACIDADES.EDTNOMBREDIAGNOSTICO.TEXT:= DATAMODULE1.QRYDIAGNOSTICOSNOM_DIAGNSOTICO.TEXT;
   FRMINCAPACIDADES.EDTCODDIAGNOSTICO.setfocus;
   FRMDIAGNOSTICOS.FREE;
   END
   ELSE IF FRMDIAGNOSTICOS.Caption='Diagnósticos Tutela' THEN
   BEGIN
   FRMINCAPACIDADESTUTELA.EDTCODDIAGNOSTICO.TEXT := DATAMODULE1.QRYDIAGNOSTICOSCOD_DIAGNOSTICO.TEXT;
   FRMINCAPACIDADESTUTELA.EDTNOMBREDIAGNOSTICO.TEXT:= DATAMODULE1.QRYDIAGNOSTICOSNOM_DIAGNSOTICO.TEXT;
   FRMINCAPACIDADESTUTELA.EDTCODDIAGNOSTICO.setfocus;
   FRMDIAGNOSTICOS.FREE;
   END
END;

procedure TFRMDIAGNOSTICOS.FormActivate(Sender: TObject);
begin
top := 7;
end;

procedure TFRMDIAGNOSTICOS.btnbuscarClick(Sender: TObject);
begin
  IF EDTBUSCAR.TEXT <> '' THEN
  BEGIN
    DATAMODULE1.dtsdiagnosticos.DataSet := DATAMODULE1.qrydiagnosticos;
    DATAMODULE1.qrydiagnosticos.CLOSE;
    DATAMODULE1.qrydiagnosticos.SQL.CLEAR;
    DATAMODULE1.qrydiagnosticos.SQL.ADD('SELECT * FROM DIAGNOSTICOS WHERE NOM_DIAGNSOTICO LIKE  :"DIAGNOSTICO" ORDER BY NOM_DIAGNSOTICO');
    DATAMODULE1.qrydiagnosticos.Parameters[0].VALUE := '%' + EDTBUSCAR.TEXT + '%';
    DATAMODULE1.qrydiagnosticos.OPEN;
    IF  DATAMODULE1.qrydiagnosticos.RECORDCOUNT = 0 THEN
    BEGIN
    SHOWMESSAGE('NO  HAY  DIAGNOSTICOS  CON ESTE  NOMBRE');
    END;
  END;
end;

procedure TFRMDIAGNOSTICOS.FormClose(Sender: TObject;
  var Action: TCloseAction);
begin
ACTION:=CAFREE;
end;

END.

