UNIT UINCAAPORNUMERO;

INTERFACE

USES
  WINDOWS, MESSAGES, SYSUTILS, VARIANTS, CLASSES, GRAPHICS, CONTROLS, FORMS,
  DIALOGS, GRIDS, DBGRIDS, STDCTRLS, EXTCTRLS, MENUS, DB, DBTABLES, Buttons,
  ADODB;

TYPE
  TFRMINCAPORNUMERO = CLASS(TFORM)
    PANEL1: TPANEL;
    PANEL2: TPANEL;
    PANEL3: TPANEL;
    LABEL2: TLABEL;
    LABEL3: TLABEL;
    EDTNOMBRE: TEDIT;
    LABEL4: TLABEL;
    CBESTADO: TCOMBOBOX;
    DBGRID1: TDBGRID;
    DBGRID2: TDBGRID;
    DTSDETALLEINC: TDATASOURCE;
    DTSENCAINC: TDATASOURCE;
    Label5: TLabel;
    Label47: TLabel;
    GroupBox1: TGroupBox;
    btnbuscar: TBitBtn;
    qryEMPRESAS: TADOQuery;
    qryEMPRESASTIP_DOCUMENTO: TStringField;
    qryEMPRESASNUM_DOCUMENTO: TStringField;
    qryEMPRESASNOM_EMPRESA: TStringField;
    qryEMPRESASREP_EMPRESA: TStringField;
    qryEMPRESASDIR_EMPRESA: TStringField;
    qryEMPRESASTEL_EPS: TStringField;
    qryEMPRESASFAX_EPS: TStringField;
    qryEMPRESASEML_EPS: TStringField;
    qryEMPRESASDEPARTAMENTO: TStringField;
    qryEMPRESASCIUDAD: TStringField;
    qryEMPRESASCOD_SUCURSAL: TStringField;
    qryEMPRESASTIP_APORTANTE: TStringField;
    qryEMPRESASCOD_ACTIVIDAD_ECO: TStringField;
    qryEMPRESASCOD_ESTADO: TStringField;
    qryEMPRESASCOD_OFICINA: TStringField;
    qryEMPRESASCOD_REGIONAL: TStringField;
    qryEMPRESASTIP_DOCUMENTO_ARP: TStringField;
    qryEMPRESASNUM_DOCUMENTO_ARP: TStringField;
    qryEMPRESASCOD_DEPARTAMENTO: TStringField;
    qryEMPRESASCOD_CIUDAD: TStringField;
    qryEMPRESASFEC_AFILIACION: TDateTimeField;
    qryEMPRESASTEL_EMPRESA: TStringField;
    qryEMPRESASTEL_EMPRESA2: TStringField;
    qryEMPRESASURL_EMPRESA: TStringField;
    qryEMPRESASEML_EMPRESA: TStringField;
    qryEMPRESASTOT_EMPLEADOS: TStringField;
    qryEMPRESASCOD_TIPO_PER: TStringField;
    qryEMPRESASCOD_ZONA: TStringField;
    qryEMPRESASCOD_DEPARTAMENTO_PAG: TStringField;
    qryEMPRESASCOD_CIUDAD_PAG: TStringField;
    qryEMPRESASCOD_PRESENTACION_cOM: TStringField;
    qryEMPRESASCOD_TIP_EMPRESA: TStringField;
    qryEMPRESASTIP_DOCUMENTO_PEN: TStringField;
    qryEMPRESASNUM_DOCUMENTO_PEN: TStringField;
    qryEMPRESASclave: TStringField;
    qryEMPRESASNOM_EMPRESA_BDUA: TStringField;
    qryEMPRESASDIGITO_VERIFICACION: TStringField;
    qryEMPRESASCARGO_REPRESENTANTE: TStringField;
    qryEMPRESASTELEFONO_REPRESENTANTE: TStringField;
    qryEMPRESASNOMBRE_CONTACTO: TStringField;
    qryEMPRESASCARGO_CONTACTO: TStringField;
    qryEMPRESASTELEFONO_CONTACTO: TStringField;
    qryEMPRESASCLASE_APORTANTE: TStringField;
    qryEMPRESASCOD_ARP: TStringField;
    qryEMPRESASCOD_ARP_BUDA: TStringField;
    qryEMPRESASBARRIO: TBCDField;
    edtnumero: TEdit;
    Edtsaldo: TEdit;
    Label1: TLabel;
    qryincapacidades2: TADOQuery;
    qryincapacidades2VALORSALDO: TBCDField;
    PROCEDURE EDTNUMEROEXIT(SENDER: TOBJECT);
    PROCEDURE CERRAR1CLICK(SENDER: TOBJECT);
    PROCEDURE BTNBUSCARCLICK(SENDER: TOBJECT);
    PROCEDURE DBGRID1CELLCLICK(COLUMN: TCOLUMN);
    PROCEDURE FORMCLOSE(SENDER: TOBJECT; VAR ACTION: TCLOSEACTION);
    PROCEDURE FORMCREATE(SENDER: TOBJECT);
    procedure FormActivate(Sender: TObject);
  PRIVATE
    { PRIVATE DECLARATIONS }
  PUBLIC
    { PUBLIC DECLARATIONS }
  END;

VAR
  FRMINCAPORNUMERO: TFRMINCAPORNUMERO;

IMPLEMENTATION

USES DTMODULO;

{$R *.DFM}

PROCEDURE TFRMINCAPORNUMERO.EDTNUMEROEXIT(SENDER: TOBJECT);
BEGIN
     IF (EDTNUMERO.TEXT > '0') THEN
     BEGIN
                EDTNOMBRE.TEXT := '';
                //*************
                DATAMODULE1.QRYINCAPACIDADES.CLOSE;
                DATAMODULE1.QRYINCAPACIDADES.SQL.CLEAR;
                DATAMODULE1.QRYINCAPACIDADES.SQL.ADD('SELECT * FROM  INCAPACIDADES WHERE NUM_INCAPACIDAD= :"NUMERO"');
                DATAMODULE1.QRYINCAPACIDADES.Parameters[0].VALUE := TRIM(EDTNUMERO.TEXT);
                DATAMODULE1.QRYINCAPACIDADES.OPEN;
                //*************
                QRYEMPRESAS.CLOSE;
                QRYEMPRESAS.SQL.CLEAR;
                QRYEMPRESAS.SQL.ADD('SELECT * FROM EMPRESAS WHERE  TIP_DOCUMENTO = :"TIPO" AND NUM_DOCUMENTO = :"NUMERO"');
                QRYEMPRESAS.Parameters[0].VALUE := DATAMODULE1.QRYINCAPACIDADESTIP_DOCEMPRESA.Value;
                QRYEMPRESAS.Parameters[1].VALUE := DATAMODULE1.QRYINCAPACIDADESNUM_DOCEMPRESA.Value;
                QRYEMPRESAS.OPEN;
                       IF DATAMODULE1.QRYINCAPACIDADES.RECORDCOUNT > 0 THEN
                        BEGIN
                        EDTNOMBRE.TEXT := QRYEMPRESASNOM_EMPRESA.Value;
                        btnbuscar.Click;
                        IF   TRIM(QRYEMPRESASCOD_ESTADO.VALUE) = 'A' THEN
                          BEGIN
                          CBESTADO.ITEMINDEX := 0;
                          END  ELSE
                                IF  TRIM(QRYEMPRESASCOD_ESTADO.VALUE) = 'S' THEN
                                        BEGIN
                                        CBESTADO.ITEMINDEX := 1;
                                        END
                                        ELSE   IF   TRIM(QRYEMPRESASCOD_ESTADO.VALUE) = 'I' THEN
                                                BEGIN
                                                CBESTADO.ITEMINDEX := 2;
                                                END;

                        END
                        ELSE SHOWMESSAGE('NO EXISTE NINGUNA  INCAPACIDAD  CON ESTE  NUMERO');
     END;

END;

PROCEDURE TFRMINCAPORNUMERO.CERRAR1CLICK(SENDER: TOBJECT);
BEGIN
FRMINCAPORNUMERO.FREE;
END;

PROCEDURE TFRMINCAPORNUMERO.BTNBUSCARCLICK(SENDER: TOBJECT);
BEGIN
     IF EDTNOMBRE.TEXT <> '' THEN
     BEGIN
     DATAMODULE1.QRYINCAPACIDADES.CLOSE;
     DATAMODULE1.QRYINCAPACIDADES.SQL.CLEAR;
     DATAMODULE1.QRYINCAPACIDADES.SQL.ADD('SELECT * FROM  INCAPACIDADES WHERE NUM_INCAPACIDAD= :"NUMERO"');
     DATAMODULE1.QRYINCAPACIDADES.Parameters[0].VALUE := TRIM(EDTNUMERO.TEXT);
     DATAMODULE1.QRYINCAPACIDADES.OPEN;
        if DATAMODULE1.QRYINCAPACIDADES.RecordCount = 0 then
        begin
         ShowMessage('LA EMPRESA NO TIENE INCAPACIDADES  DIGITADAS');
         END;
         if DATAMODULE1.QRYINCAPACIDADES.RecordCount > 0 then
         BEGIN
         QRYINCAPACIDADES2.CLOSE;
         QRYINCAPACIDADES2.Parameters[0].VALUE := TRIM(EDTNUMERO.TEXT);
         QRYINCAPACIDADES2.OPEN;
         EDTSALDO.Text := '$ ' + QRYINCAPACIDADES2VALORSALDO.Text;
         END
     END;

END;

PROCEDURE TFRMINCAPORNUMERO.DBGRID1CELLCLICK(COLUMN: TCOLUMN);
BEGIN
             DATAMODULE1.QRYDETINCAPACIDAD.CLOSE;
             DATAMODULE1.QRYDETINCAPACIDAD.SQL.CLEAR;
             DATAMODULE1.QRYDETINCAPACIDAD.SQL.ADD('SELECT * FROM DET_INCAPACIDAD WHERE NUM_INCAPACIDAD = :"INCAP"');
             DATAMODULE1.QRYDETINCAPACIDAD.Parameters[0].VALUE := TRIM(EDTNUMERO.TEXT);
             DATAMODULE1.QRYDETINCAPACIDAD.OPEN;

END;

PROCEDURE TFRMINCAPORNUMERO.FORMCLOSE(SENDER: TOBJECT;
  VAR ACTION: TCLOSEACTION);
BEGIN
  ACTION := CAFREE;
END;

PROCEDURE TFRMINCAPORNUMERO.FORMCREATE(SENDER: TOBJECT);
BEGIN
DATAMODULE1.QRYDETINCAPACIDAD.CLOSE;
DATAMODULE1.QRYINCAPACIDADES.CLOSE;
EDTSALDO.Text :='0';
END;



procedure TFRMINCAPORNUMERO.FormActivate(Sender: TObject);
begin
WindowState := wsNormal;
top := 0;
Left := 0;
end;

END.

