UNIT UMODESTRATO;

INTERFACE

USES
  WINDOWS, MESSAGES, SYSUTILS, CLASSES, GRAPHICS, CONTROLS, FORMS,
  DIALOGS, GRIDS, DBGRIDS, DBCTRLS, EXTCTRLS, DB, DBTABLES, STDCTRLS,
  COMCTRLS, MENUS;

TYPE
  TFRMMODIFICARESTRATO = CLASS(TFORM)
    PANEL1: TPANEL;
    PANEL3: TPANEL;
    DBGRID2: TDBGRID;
    PANEL4: TPANEL;
    DBGRID1: TDBGRID;
    SPLITTER1: TSPLITTER;
    PANEL2: TPANEL;
    BUTTON1: TBUTTON;
    Label47: TLabel;
    Label48: TLabel;
    HeaderControl1: THeaderControl;
    GroupBox1: TGroupBox;
    Label1: TLabel;
    cbbancos: TDBLookupComboBox;
    Label2: TLabel;
    dtfinicial: TDateTimePicker;
    Label3: TLabel;
    dtffinal: TDateTimePicker;
    Label4: TLabel;
    Label5: TLabel;
    PROCEDURE FORMCREATE(SENDER: TOBJECT);
    PROCEDURE BUTTON1CLICK(SENDER: TOBJECT);
    PROCEDURE DTFFINALEXIT(SENDER: TOBJECT);
    PROCEDURE FORMCLOSE(SENDER: TOBJECT; VAR ACTION: TCLOSEACTION);
    PROCEDURE CERRAR1CLICK(SENDER: TOBJECT);
    PROCEDURE APPMESSAGE(VAR MSG: TMSG; VAR HANDLED: BOOLEAN);
    procedure DBGrid2CellClick(Column: TColumn);
    procedure cbbancosExit(Sender: TObject);
    procedure FormActivate(Sender: TObject);

  PRIVATE
    { PRIVATE DECLARATIONS }
  PUBLIC
    { PUBLIC DECLARATIONS }
  END;

VAR
  FRMMODIFICARESTRATO: TFRMMODIFICARESTRATO;

IMPLEMENTATION

USES DTMODULO, UGLOBAL;

{$R *.DFM}

PROCEDURE TFRMMODIFICARESTRATO.FORMCREATE(SENDER: TOBJECT);
VAR ANO,MES : STRING;
BEGIN
        APPLICATION.ONMESSAGE := APPMESSAGE;
        DTFINICIAL.DATE := STRTODATE(GLDATE);
        DTFFINAL.DATE := STRTODATE(GLDATE);
        DATAMODULE1.QRYBANCOS.OPEN;
        DATAMODULE1.qryestrato.CLOSE;
        DATAMODULE1.qryautoliquidacion.CLOSE;

END;

PROCEDURE TFRMMODIFICARESTRATO.BUTTON1CLICK(SENDER: TOBJECT);
VAR PLANILLA,EMPRESA : STRING;
    EXTRACTO : REAL;
    DOCUMENTO,TIPO : STRING;
    FECHA_RECAUDO : TDATETIME;
    VALOR_CONSIGNADO : REAL;
BEGIN
//        IF (DATAMODULE1.QRYAUTOLIQUIDACIONTOT_PAGADO.VALUE = DATAMODULE1.QRYESTRATOVAL_CONSIGNACION.VALUE ) AND (DATAMODULE1.QRYAUTOLIQUIDACIONFEC_PAGO.VALUE = DATAMODULE1.QRYESTRATOFEC_RECAUDO.VALUE ) THEN
  //      BEGIN
//         IF  COPY((DATAMODULE1.QRYAUTOLIQUIDACIONEMP_NUMERO_DOC.VALUE),1, 5) = COPY((DATAMODULE1.QRYESTRATONUM_DOCUMENTO.VALUE),1, 5) THEN
 //         BEGIN
        PLANILLA := '0';
        EXTRACTO := 0;
        PLANILLA := DATAMODULE1.QRYAUTOLIQUIDACIONNUM_PLANILLA.VALUE;
        EMPRESA := DATAMODULE1.QRYAUTOLIQUIDACIONEMP_NUMERO_DOC.VALUE;
        FECHA_RECAUDO := DATAMODULE1.QRYESTRATOFEC_RECAUDO.VALUE;
        VALOR_CONSIGNADO := DATAMODULE1.QRYESTRATOVAL_CONSIGNACION.VALUE;
        TIPO := DATAMODULE1.QRYESTRATOTIP_MOVIMIENTO.VALUE;
        DOCUMENTO := TRIM(DATAMODULE1.QRYESTRATONUM_DOCUMENTO.VALUE);
        DATAMODULE1.QRYAUTOLIQUIDACION.CLOSE;

        DATAMODULE1.QRYAUTOLIQUIDACION.SQL.CLEAR;
        DATAMODULE1.QRYAUTOLIQUIDACION.SQL.ADD('SELECT *  FROM AUTOLIQUIDACION WHERE NUM_PLANILLA = :"PLANILLA"');
        DATAMODULE1.QRYAUTOLIQUIDACION.Parameters[0].Value := PLANILLA;
        DATAMODULE1.QRYAUTOLIQUIDACION.OPEN;
        IF DATAMODULE1.QRYAUTOLIQUIDACION.RECORDCOUNT = 1 THEN
        BEGIN
          DATAMODULE1.QRYESTRATO.CLOSE;
          DATAMODULE1.QRYESTRATO.SQL.CLEAR;
          DATAMODULE1.QRYESTRATO.SQL.ADD('SELECT * FROM EST_BANCARIO_AUTO WHERE NUM_DOCUMENTO = :"DOCUMENTO" AND FEC_RECAUDO = :"FECHA_RECAUDO" AND VAL_CONSIGNACION = :"VALOR_CONSIGNADO" AND TIP_MOVIMIENTO = :"TIPO"');
          DATAMODULE1.QRYESTRATO.Parameters[0].Value :=  DOCUMENTO;
          DATAMODULE1.QRYESTRATO.Parameters[1].Value :=  FECHA_RECAUDO;
          DATAMODULE1.QRYESTRATO.Parameters[2].Value :=  VALOR_CONSIGNADO;
          DATAMODULE1.QRYESTRATO.Parameters[3].Value :=  TIPO;
          DATAMODULE1.QRYESTRATO.OPEN;
          IF DATAMODULE1.QRYESTRATO.RECORDCOUNT = 1 THEN
          BEGIN
            // CONCILIAR  EL EXTRACTO
            DATAMODULE1.qryestrato.First;
            DATAMODULE1.QRYESTRATO.EDIT;
            DATAMODULE1.QRYESTRATOEST_CONCILIACION.VALUE := 'S';
            DATAMODULE1.QRYESTRATONUM_PLANILLA.VALUE := PLANILLA;
            DATAMODULE1.QRYESTRATOFEC_PLANILLA_CON.VALUE := STRTODATE(GLDATE);
            DATAMODULE1.QRYESTRATONUM_DOCUMENTO.VALUE := EMPRESA;
            DATAMODULE1.QRYESTRATO.POST;
            DATAMODULE1.QRYESTRATO.CLOSE;
            // CONCILIAR  LA PLANILLA
            DATAMODULE1.qryautoliquidacion.First;
            DATAMODULE1.QRYAUTOLIQUIDACION.EDIT;
            DATAMODULE1.QRYAUTOLIQUIDACIONCRU_CONCILIACION.VALUE := 'S';
            DATAMODULE1.QRYAUTOLIQUIDACION.POST;
            DATAMODULE1.QRYAUTOLIQUIDACION.CLOSE;
            SHOWMESSAGE('LA PLANILLA  FUE CONCILIADA');
            // LLENAR  NUEVAMENTE  LOS  DBCRILLAS
            DATAMODULE1.QRYESTRATO.CLOSE;
            DATAMODULE1.QRYESTRATO.SQL.CLEAR;
            DATAMODULE1.QRYESTRATO.SQL.ADD('SELECT *  FROM EST_BANCARIO_AUTO WHERE (FEC_RECAUDO >= :"INICIAL" AND  FEC_RECAUDO <= :"FINAL") AND  (EST_CONCILIACION = :"ESTADO") AND COD_BANCO = :"BANCO" ORDER BY FEC_RECAUDO,VAL_CONSIGNACION,NUM_DOCUMENTO');
            DATAMODULE1.QRYESTRATO.Parameters[0].Value :=  (DTFINICIAL.DATE);
            DATAMODULE1.QRYESTRATO.Parameters[1].Value := (DTFFINAL.DATE);
            DATAMODULE1.QRYESTRATO.Parameters[2].Value := 'N';
            DATAMODULE1.QRYESTRATO.Parameters[3].Value := CBBANCOS.KEYVALUE;
            DATAMODULE1.QRYESTRATO.OPEN;
            IF DATAMODULE1.QRYESTRATO.RECORDCOUNT = 0 THEN
            BEGIN
              SHOWMESSAGE('NO HAY  ESTRACTOS  BANCARIOS  EN EL BANCO'+  CBBANCOS.TEXT + ' PARA CONTINUAR CONCILIAR');
            END
            ELSE IF DATAMODULE1.QRYESTRATO.RECORDCOUNT > 0 THEN
            BEGIN
                //*************************EJECUTAR  AUTOLIQUIDACIONES
              DATAMODULE1.QRYAUTOLIQUIDACION.CLOSE;
              DATAMODULE1.QRYAUTOLIQUIDACION.SQL.CLEAR;
              DATAMODULE1.QRYAUTOLIQUIDACION.SQL.ADD('SELECT *  FROM AUTOLIQUIDACION WHERE (FEC_PAGO >= :"INICIAL" AND  FEC_PAGO <= :"FINAL") AND ((CRU_CONCILIACION <> :"ESTADO")  OR (CRU_CONCILIACION IS NULL))  ORDER BY FEC_PAGO,TOT_PAGADO,EMP_NUMERO_DOC');
              DATAMODULE1.QRYAUTOLIQUIDACION.Parameters[0].Value :=  (DTFINICIAL.DATE);
              DATAMODULE1.QRYAUTOLIQUIDACION.Parameters[1].Value := (DTFFINAL.DATE);
              DATAMODULE1.QRYAUTOLIQUIDACION.Parameters[2].Value := 'S';
              DATAMODULE1.QRYAUTOLIQUIDACION.OPEN;
            END;
          END;
        END;
     //                    END ELSE
     //   SHOWMESSAGE(' NO  COINCIDEN  LOS PRIMEROS 5  DIGITOS DE LA  EMPRESA' );
      //  END ELSE
       // SHOWMESSAGE(' NO COICIDE LA  FECHA  DE  PAGO Y VALOR  PAGADO' );
END;

PROCEDURE TFRMMODIFICARESTRATO.DTFFINALEXIT(SENDER: TOBJECT);
BEGIN
        IF CBBANCOS.KEYVALUE <> '' THEN
        BEGIN
                DATAMODULE1.QRYESTRATO.CLOSE;
                DATAMODULE1.QRYESTRATO.SQL.CLEAR;
                DATAMODULE1.QRYESTRATO.SQL.ADD('SELECT *  FROM EST_BANCARIO_AUTO WHERE (FEC_RECAUDO >= :"INICIAL" AND  FEC_RECAUDO <= :"FINAL") AND  (EST_CONCILIACION = :"ESTADO") AND COD_BANCO = :"BANCO" ORDER BY FEC_RECAUDO,VAL_CONSIGNACION,NUM_DOCUMENTO');
                DATAMODULE1.QRYESTRATO.Parameters[0].DataType := ftDateTime; 
                DATAMODULE1.QRYESTRATO.Parameters[1].DataType := ftDateTime; 
                DATAMODULE1.QRYESTRATO.Parameters[0].Value :=  (DTFINICIAL.DATE);
                DATAMODULE1.QRYESTRATO.Parameters[1].Value := (DTFFINAL.DATE);
                DATAMODULE1.QRYESTRATO.Parameters[2].Value := 'N';
                DATAMODULE1.QRYESTRATO.Parameters[3].Value := CBBANCOS.KEYVALUE;
                DATAMODULE1.QRYESTRATO.OPEN;
                        IF DATAMODULE1.QRYESTRATO.RECORDCOUNT = 0 THEN
                        BEGIN
                        SHOWMESSAGE('NO HAY  ESTRACTOS  BANCARIOS  PARA  CONCILIAR');
                        END
                        ELSE    IF DATAMODULE1.QRYESTRATO.RECORDCOUNT > 0 THEN
                                BEGIN
                                DATAMODULE1.QRYAUTOLIQUIDACION.CLOSE;
                                DATAMODULE1.QRYAUTOLIQUIDACION.SQL.CLEAR;
                                DATAMODULE1.QRYAUTOLIQUIDACION.SQL.ADD('SELECT *  FROM AUTOLIQUIDACION WHERE (FEC_PAGO >= :"INICIAL" AND  FEC_PAGO <= :"FINAL") AND ((CRU_CONCILIACION <> :"ESTADO")  OR (CRU_CONCILIACION IS NULL)) ORDER BY FEC_PAGO,TOT_PAGADO,EMP_NUMERO_DOC');
                                DATAMODULE1.QRYESTRATO.Parameters[0].DataType := ftDateTime; 
                		DATAMODULE1.QRYESTRATO.Parameters[1].DataType := ftDateTime; 
                                DATAMODULE1.QRYAUTOLIQUIDACION.Parameters[0].Value :=  (DTFINICIAL.DATE);
                                DATAMODULE1.QRYAUTOLIQUIDACION.Parameters[1].Value := (DTFFINAL.DATE);
                                DATAMODULE1.QRYAUTOLIQUIDACION.Parameters[2].Value := 'S';
                                DATAMODULE1.QRYAUTOLIQUIDACION.OPEN;
                                END;
        END ELSE SHOWMESSAGE('ESCOJA  EL  BANCO PARA  REALIZAR LA  CONCILIACION');
END;

PROCEDURE TFRMMODIFICARESTRATO.FORMCLOSE(SENDER: TOBJECT;
  VAR ACTION: TCLOSEACTION);
BEGIN
ACTION := CAFREE;
END;

PROCEDURE TFRMMODIFICARESTRATO.CERRAR1CLICK(SENDER: TOBJECT);
BEGIN
FRMMODIFICARESTRATO.CLOSE;
END;

procedure TFRMMODIFICARESTRATO.APPMESSAGE(var MSG: TMSG;
  var HANDLED: BOOLEAN);
begin
  IF MSG.WPARAM = VK_RETURN THEN
       BEGIN
        IF ((SCREEN.ACTIVECONTROL) IS TCOMBOBOX) THEN
             MSG.WPARAM := VK_TAB;
            IF (((SCREEN.ACTIVECONTROL) IS TEDIT)) THEN
                MSG.WPARAM := VK_TAB;
                IF ((SCREEN.ACTIVECONTROL) IS TDBEDIT) THEN
                MSG.WPARAM := VK_TAB;
                IF ((SCREEN.ACTIVECONTROL) IS TDateTimePicker) THEN
                MSG.WPARAM := VK_TAB;
                IF ((SCREEN.ACTIVECONTROL) IS TDBGrid) THEN
                MSG.WPARAM := VK_TAB;
                IF ((SCREEN.ACTIVECONTROL) IS TDBLOOKUPCOMBOBOX) THEN
                MSG.WPARAM := VK_TAB;
                IF ((SCREEN.ACTIVECONTROL) IS TStringGrid) THEN
                MSG.WPARAM := VK_TAB;
                IF ((SCREEN.ACTIVECONTROL) IS TCheckBox) THEN
                MSG.WPARAM := VK_TAB;
       END;

end;

procedure TFRMMODIFICARESTRATO.DBGrid2CellClick(Column: TColumn);
begin
                DATAMODULE1.QRYAUTOLIQUIDACION.SQL.Clear;
                DATAMODULE1.QRYAUTOLIQUIDACION.CLOSE;
                DATAMODULE1.QRYAUTOLIQUIDACION.SQL.ADD('SELECT *  FROM AUTOLIQUIDACION WHERE (FEC_PAGO >= :"FECHAI" AND  FEC_PAGO <= :"FECHAF") AND ((CRU_CONCILIACION <> :"ESTADO")  OR (CRU_CONCILIACION IS NULL)) ORDER BY FEC_PAGO,TOT_PAGADO,EMP_NUMERO_DOC');
                DATAMODULE1.QRYAUTOLIQUIDACION.Parameters[0].Value := DATAMODULE1.qryestratoFEC_RECAUDO.Value;
                DATAMODULE1.QRYAUTOLIQUIDACION.Parameters[1].Value := DATAMODULE1.qryestratoFEC_RECAUDO.Value;
                DATAMODULE1.QRYAUTOLIQUIDACION.Parameters[2].Value := 'S';
                DATAMODULE1.QRYAUTOLIQUIDACION.OPEN;
                  IF DATAMODULE1.QRYAUTOLIQUIDACION.RECORDCOUNT = 0 THEN
                  BEGIN
                SHOWMESSAGE(LowerCase('NO HAY  AUTOLIQUIDACIONES  CON ESTE  VALOR'));
                END;


end;

procedure TFRMMODIFICARESTRATO.cbbancosExit(Sender: TObject);
begin
        IF TRIM(CBBANCOS.TEXT) = '' THEN
        BEGIN
        ShowMessage('Seleccione  el  banco  para  continuar');
        END
        ELSE
        BEGIN
                DATAMODULE1.QRYESTRATO.CLOSE;
                DATAMODULE1.QRYESTRATO.SQL.CLEAR;
                DATAMODULE1.QRYESTRATO.SQL.ADD('SELECT *  FROM EST_BANCARIO_AUTO WHERE (FEC_RECAUDO >= :"INICIAL" AND  FEC_RECAUDO <= :"FINAL") AND  (EST_CONCILIACION = :"ESTADO") AND COD_BANCO = :"BANCO" ORDER BY FEC_RECAUDO,VAL_CONSIGNACION,NUM_DOCUMENTO');
                DATAMODULE1.QRYESTRATO.Parameters[0].DataType := ftDateTime; 
                DATAMODULE1.QRYESTRATO.Parameters[1].DataType := ftDateTime; 
                
                DATAMODULE1.QRYESTRATO.Parameters[0].Value :=  (DTFINICIAL.DATE);
                DATAMODULE1.QRYESTRATO.Parameters[1].Value := (DTFFINAL.DATE);
                DATAMODULE1.QRYESTRATO.Parameters[2].Value := 'N';
                DATAMODULE1.QRYESTRATO.Parameters[3].Value := CBBANCOS.KEYVALUE;
                DATAMODULE1.QRYESTRATO.OPEN;
                        IF DATAMODULE1.QRYESTRATO.RECORDCOUNT > 0 THEN
                           BEGIN
                                DATAMODULE1.QRYAUTOLIQUIDACION.CLOSE;
                                DATAMODULE1.QRYAUTOLIQUIDACION.SQL.CLEAR;
                                DATAMODULE1.QRYAUTOLIQUIDACION.SQL.ADD('SELECT *  FROM AUTOLIQUIDACION WHERE (FEC_PAGO >= :"INICIAL" AND  FEC_PAGO <= :"FINAL") AND ((CRU_CONCILIACION <> :"ESTADO")  OR (CRU_CONCILIACION IS NULL)) ORDER BY FEC_PAGO,TOT_PAGADO,EMP_NUMERO_DOC');
                                DATAMODULE1.QRYAUTOLIQUIDACION.Parameters[0].Value :=  (DTFINICIAL.DATE);
                                DATAMODULE1.QRYAUTOLIQUIDACION.Parameters[1].Value := (DTFFINAL.DATE);
                                DATAMODULE1.QRYAUTOLIQUIDACION.Parameters[2].Value := 'S';
                                DATAMODULE1.QRYAUTOLIQUIDACION.OPEN;
                           end;
        END;
end;

procedure TFRMMODIFICARESTRATO.FormActivate(Sender: TObject);
begin
WindowState := wsNormal;
top := 0;
Left := 0;
end;

END.

