SELECT COMISIONES.*, ACESORES.PRI_APELLIDO, ACESORES.PRI_NOMBRE, AFILIADOS.PRI_APELLIDO, AFILIADOS.PRI_NOMBRE, NOM_EMPRESA
FROM COMISIONES, ACESORES,AFILIADOS, AFILIADOS_COMPENSADOS,EMPRESAS
WHERE FEC_CORTE = '08/01/2003'
AND NUM_DOCUMENTO_ASE = ACESORES.NUM_DOCUMENTO
AND NUM_DOCUMENTO_AFI = AFILIADOS.NUM_DOCUMENTO
AND NUM_DOCUMENTO_AFI = AFI_NUMERO_DOC
AND COMISIONES.NUM_DECLARACION = AFILIADOS_COMPENSADOS.NUM_DECLARACION
AND AFILIADOS_COMPENSADOS.EMP_NUMERO_DOC = EMPRESAS.NUM_DOCUMENTO;