UNIT UAFILIADOS;

INTERFACE

USES
  WINDOWS, MESSAGES, SYSUTILS, VARIANTS, CLASSES, GRAPHICS, CONTROLS, FORMS,
  DIALOGS, GRIDS, DBGRIDS, DBCTRLS, EXTCTRLS, DB, DBTABLES;

TYPE
  TFRMAFILIADOS = CLASS(TFORM)
    PANEL1: TPANEL;
    PANEL2: TPANEL;
    DBNAVIGATOR1: TDBNAVIGATOR;
    DBGRID1: TDBGRID;
    DTSAFILIADOS: TDATASOURCE;
    PROCEDURE FORMCREATE(SENDER: TOBJECT);
    PROCEDURE FORMCLOSE(SENDER: TOBJECT; VAR ACTION: TCLOSEACTION);
    PROCEDURE DBGRID1DBLCLICK(SENDER: TOBJECT);
    PROCEDURE AUTILIQUIDACIONES;
    PROCEDURE INCAPACIDADES;
    PROCEDURE CORRECIONES;
  PRIVATE
    { PRIVATE DECLARATIONS }
  PUBLIC
    { PUBLIC DECLARATIONS }
  END;

VAR
  FRMAFILIADOS: TFRMAFILIADOS;

IMPLEMENTATION

USES DTMODULO, UPLANILLAS, UINCAPACIDADES, UGLOBAL, Uplanillacorreciones;

{$R *.DFM}

PROCEDURE TFRMAFILIADOS.FORMCREATE(SENDER: TOBJECT);
BEGIN
    DATAMODULE1.QRYAFILIADOS.CLOSE;
    DATAMODULE1.QRYAFILIADOS.PREPARE;
    DATAMODULE1.QRYAFILIADOS.SQL.CLEAR;
    DATAMODULE1.QRYAFILIADOS.SQL.ADD('SELECT  TIP_DOCUMENTO_EMP, NUM_DOCUMENTO_EMP,TIP_DOCUMENTO_AFI, NUM_DOCUMENTO_AFI,PRI_APELLIDO,SEG_APELLIDO,PRI_NOMBRE,SEG_NOMBRE,VAL_SUELDO_AFIL,FEC_INGRESO_UNI,FEC_EGRESO_UNI,AFILIADOS_EMPRESAS.COD_ESTADO,FEC_NACIMIENTO,COD_SEXO,COD_MODALIDAD_TRA');
    DATAMODULE1.QRYAFILIADOS.SQL.ADD(' FROM AFILIADOS_EMPRESAS,AFILIADOS');
    DATAMODULE1.QRYAFILIADOS.SQL.ADD('WHERE TIP_DOCUMENTO_AFI = TIP_DOCUMENTO AND NUM_DOCUMENTO_AFI = NUM_DOCUMENTO AND TIP_DOCUMENTO_EMP = :"NIT" AND NUM_DOCUMENTO_EMP = :"DOCUMENTO" AND AFILIADOS_EMPRESAS.COD_ESTADO = :"ESTADO" ORDER BY PRI_APELLIDO,SEG_APELLIDO,PRI_NOMBRE,SEG_NOMBRE');
    IF GLPROCESO = 'AUTOLIQUIDACIONES' THEN
    BEGIN
        DATAMODULE1.QRYAFILIADOS.PARAMS[0].ASSTRING := FRMPLANILLAS.CBTIPODOCEMPRESA.TEXT;
        DATAMODULE1.QRYAFILIADOS.PARAMS[1].ASSTRING := FRMPLANILLAS.EDNUMERO.TEXT;
        DATAMODULE1.QRYAFILIADOS.PARAMS[2].ASSTRING := 'A';
    END
    ELSE IF GLPROCESO = 'INCAPACIDADES' THEN
    BEGIN
        DATAMODULE1.QRYAFILIADOS.PARAMS[0].ASSTRING := TRIM(FRMINCAPACIDADES.CBTIPODOCEMPRESA.TEXT);
        DATAMODULE1.QRYAFILIADOS.PARAMS[1].ASSTRING := TRIM(FRMINCAPACIDADES.EDTNUMDOCEMPRESA.TEXT);
        DATAMODULE1.QRYAFILIADOS.PARAMS[2].ASSTRING := 'A';
        END
        else IF GLPROCESO = 'CORRECIONES' THEN
    BEGIN
        DATAMODULE1.QRYAFILIADOS.PARAMS[0].ASSTRING := TRIM(frmcorreciones.cbtipodocempresa.TEXT);
        DATAMODULE1.QRYAFILIADOS.PARAMS[1].ASSTRING := TRIM(frmcorreciones.edtnumeroducafiliado.TEXT);
        DATAMODULE1.QRYAFILIADOS.PARAMS[2].ASSTRING := 'A';
        END;
     DATAMODULE1.QRYAFILIADOS.OPEN;
    IF DATAMODULE1.QRYAFILIADOS.RECORDCOUNT = 0 THEN
      BEGIN
       SHOWMESSAGE('NO EXISTEN AFILIADOS  POR  ESTA  EMPRESA');
       END;
    END;

PROCEDURE TFRMAFILIADOS.FORMCLOSE(SENDER: TOBJECT;
  VAR ACTION: TCLOSEACTION);
BEGIN
ACTION:=CAFREE;
END;

PROCEDURE TFRMAFILIADOS.DBGRID1DBLCLICK(SENDER: TOBJECT);
BEGIN
IF GLPROCESO = 'AUTOLIQUIDACIONES' THEN
   BEGIN
   AUTILIQUIDACIONES;
   END
       ELSE IF GLPROCESO = 'INCAPACIDADES' THEN
       BEGIN
       INCAPACIDADES;
       END
       ELSE IF GLPROCESO = 'CORRECIONES' THEN
            BEGIN
            CORRECIONES;
            END;
       
END;
PROCEDURE TFRMAFILIADOS.AUTILIQUIDACIONES;
BEGIN
IF DATAMODULE1.QRYAFILIADOSTIP_DOCUMENTO_AFI.TEXT = 'CC' THEN
    BEGIN
    FRMPLANILLAS.CBTIPODOCAFILIADO.ITEMINDEX := 0;
    END
      ELSE IF DATAMODULE1.QRYAFILIADOSTIP_DOCUMENTO_AFI.TEXT = 'CE' THEN
              BEGIN
              FRMPLANILLAS.CBTIPODOCAFILIADO.ITEMINDEX := 1;
              END
              ELSE IF DATAMODULE1.QRYAFILIADOSTIP_DOCUMENTO_AFI.TEXT = 'TI' THEN
                   BEGIN
                   FRMPLANILLAS.CBTIPODOCAFILIADO.ITEMINDEX := 2;
                   END;

    FRMPLANILLAS.EDTNUMERODUCAFILIADO.TEXT := DATAMODULE1.QRYAFILIADOSNUM_DOCUMENTO_AFI.TEXT;
    FRMPLANILLAS.EDTNOMBREAFILIADO.TEXT := DATAMODULE1.QRYAFILIADOSPRI_APELLIDO.VALUE + ' ' + DATAMODULE1.QRYAFILIADOSSEG_APELLIDO.VALUE + ' ' + DATAMODULE1.QRYAFILIADOSPRI_NOMBRE.VALUE + ' ' + DATAMODULE1.QRYAFILIADOSSEG_NOMBRE.VALUE;
    FRMAFILIADOS.FREE;
    FRMPLANILLAS.EDTNUMERODUCAFILIADO.SETFOCUS;
END;

PROCEDURE TFRMAFILIADOS.INCAPACIDADES;
BEGIN
IF DATAMODULE1.QRYAFILIADOSTIP_DOCUMENTO_AFI.TEXT = 'CC' THEN
    BEGIN
    FRMINCAPACIDADES.CBTIPODOCAFILIADO.ITEMINDEX := 0;
    END
      ELSE IF DATAMODULE1.QRYAFILIADOSTIP_DOCUMENTO_AFI.TEXT = 'CE' THEN
              BEGIN
              FRMINCAPACIDADES.CBTIPODOCAFILIADO.ITEMINDEX := 1;
              END
              ELSE IF DATAMODULE1.QRYAFILIADOSTIP_DOCUMENTO_AFI.TEXT = 'TI' THEN
                   BEGIN
                   FRMINCAPACIDADES.CBTIPODOCAFILIADO.ITEMINDEX := 2;
                   END;


    FRMINCAPACIDADES.EDTNUMDOCAFILIADOIN.TEXT := DATAMODULE1.QRYAFILIADOSNUM_DOCUMENTO_AFI.TEXT;
    FRMINCAPACIDADES.EDTNOMBREAFILIADO.TEXT := DATAMODULE1.QRYAFILIADOSPRI_APELLIDO.VALUE + ' ' + DATAMODULE1.QRYAFILIADOSSEG_APELLIDO.VALUE + ' ' + DATAMODULE1.QRYAFILIADOSPRI_NOMBRE.VALUE + ' ' + DATAMODULE1.QRYAFILIADOSSEG_NOMBRE.VALUE;
    FRMAFILIADOS.FREE;
    FRMINCAPACIDADES.EDTNUMDOCAFILIADOIN.SetFocus;



END;

procedure TFRMAFILIADOS.CORRECIONES;
begin
IF DATAMODULE1.QRYAFILIADOSTIP_DOCUMENTO_AFI.TEXT = 'CC' THEN
    BEGIN
    frmcorreciones.CBTIPODOCAFILIADO.ITEMINDEX := 0;
    END
      ELSE IF DATAMODULE1.QRYAFILIADOSTIP_DOCUMENTO_AFI.TEXT = 'CE' THEN
              BEGIN
              frmcorreciones.CBTIPODOCAFILIADO.ITEMINDEX := 1;
              END
              ELSE IF DATAMODULE1.QRYAFILIADOSTIP_DOCUMENTO_AFI.TEXT = 'TI' THEN
                   BEGIN
                   frmcorreciones.CBTIPODOCAFILIADO.ITEMINDEX := 2;
                   END;

    frmcorreciones.EDTNUMERODUCAFILIADO.TEXT := DATAMODULE1.QRYAFILIADOSNUM_DOCUMENTO_AFI.TEXT;
    frmcorreciones.EDTNOMBREAFILIADO.TEXT := DATAMODULE1.QRYAFILIADOSPRI_APELLIDO.VALUE + ' ' + DATAMODULE1.QRYAFILIADOSSEG_APELLIDO.VALUE + ' ' + DATAMODULE1.QRYAFILIADOSPRI_NOMBRE.VALUE + ' ' + DATAMODULE1.QRYAFILIADOSSEG_NOMBRE.VALUE;
    FRMAFILIADOS.FREE;
    frmcorreciones.EDTNUMERODUCAFILIADO.SETFOCUS;

end;

END.

