UNIT UEMPRESAS;

INTERFACE

USES
  WINDOWS, MESSAGES, CLASSES, SYSUTILS, GRAPHICS, CONTROLS, STDCTRLS, FORMS,
  DIALOGS, DBCTRLS, DB, DBGRIDS, GRIDS, EXTCTRLS;

TYPE
  TFRMEMPRESAS = CLASS(TFORM)
    DBGRID1: TDBGRID;
    DBNAVIGATOR: TDBNAVIGATOR;
    PANEL1: TPANEL;
    PANEL2: TPANEL;
    LABEL1: TLABEL;
    EDTBUSCAR: TEDIT;
    BTNBUSCAR: TBUTTON;
    PROCEDURE FORMCREATE(SENDER: TOBJECT);
    PROCEDURE FORMCLOSE(SENDER: TOBJECT; VAR ACTION: TCLOSEACTION);
    PROCEDURE AUTOLIQUIDACIONES;
    PROCEDURE INCAPACIDADES;
    PROCEDURE DBGRID1DBLCLICK(SENDER: TOBJECT);
    PROCEDURE BTNBUSCARCLICK(SENDER: TOBJECT);
    PROCEDURE CORRECION_AUTOLIQUIDACIONES;

  PRIVATE
    { PRIVATE DECLARATIONS }
  PUBLIC
    { PUBLIC DECLARATIONS }
  END;

VAR
  FRMEMPRESAS: TFRMEMPRESAS;

IMPLEMENTATION

USES UGLOBAL, DTMODULO, UPLANILLAS, UINCAPACIDADES, Uplanillacorreciones;

{$R *.DFM}

PROCEDURE TFRMEMPRESAS.FORMCREATE(SENDER: TOBJECT);
BEGIN
    DATAMODULE1.DTSEMPRESAS.DATASET := DATAMODULE1.QRYLISTAEMPRESAS;
    DATAMODULE1.QRYLISTAEMPRESAS.CLOSE;
    DATAMODULE1.QRYLISTAEMPRESAS.PREPARE;
    DATAMODULE1.QRYLISTAEMPRESAS.SQL.CLEAR;
    DATAMODULE1.QRYLISTAEMPRESAS.SQL.ADD('SELECT * FROM EMPRESAS  ORDER BY NOM_EMPRESA');
 //  DATAMODULE1.QRYLISTAEMPRESAS.PARAMS[0].ASSTRING := 'A';
    DATAMODULE1.QRYLISTAEMPRESAS.OPEN;


END;

PROCEDURE TFRMEMPRESAS.FORMCLOSE(SENDER: TOBJECT;
  VAR ACTION: TCLOSEACTION);
BEGIN
ACTION:=CAFREE;
END;

PROCEDURE TFRMEMPRESAS.AUTOLIQUIDACIONES;
VAR TIPO : STRING;
BEGIN
  // DATAMODULE1.QRYLISTAEMPRESAS.EDIT;
    IF DATAMODULE1.QRYLISTAEMPRESASTIP_DOCUMENTO.TEXT = 'NIT' THEN
    BEGIN
    FRMPLANILLAS.CBTIPODOCEMPRESA.ITEMINDEX := 1;
    END
    ELSE IF DATAMODULE1.QRYLISTAEMPRESASTIP_DOCUMENTO.TEXT = 'CC' THEN
         BEGIN
         FRMPLANILLAS.CBTIPODOCEMPRESA.ITEMINDEX := 0;
         END
         ELSE IF DATAMODULE1.QRYLISTAEMPRESASTIP_DOCUMENTO.TEXT = 'CE' THEN
              BEGIN
              FRMPLANILLAS.CBTIPODOCEMPRESA.ITEMINDEX := 2;
              END
              ELSE IF DATAMODULE1.QRYLISTAEMPRESASTIP_DOCUMENTO.TEXT = 'TI' THEN
                   BEGIN
                   FRMPLANILLAS.CBTIPODOCEMPRESA.ITEMINDEX := 3;
                   END;

   FRMPLANILLAS.EDNUMERO.TEXT := DATAMODULE1.QRYLISTAEMPRESASNUM_DOCUMENTO.TEXT;
   //FRMPLANILLAS.EDTSUCURSAL.TEXT:= DATAMODULE1.QRYLISTAEMPRESASCOD_SUCURSAL.TEXT;
   FRMPLANILLAS.EDTNOMBREEMPRESA.TEXT:= DATAMODULE1.QRYLISTAEMPRESASNOM_EMPRESA.TEXT;
   FRMEMPRESAS.FREE;
   FRMPLANILLAS.EDNUMERO.SetFocus;


END;

PROCEDURE TFRMEMPRESAS.INCAPACIDADES;
VAR TIPO : STRING;
BEGIN
 // DATAMODULE1.QRYLISTAEMPRESAS.EDIT;
    IF DATAMODULE1.QRYLISTAEMPRESASTIP_DOCUMENTO.TEXT = 'NIT' THEN
    BEGIN
    FRMINCAPACIDADES.CBTIPODOCEMPRESA.ITEMINDEX := 1;
    END
    ELSE IF DATAMODULE1.QRYLISTAEMPRESASTIP_DOCUMENTO.TEXT = 'CC' THEN
         BEGIN
         FRMINCAPACIDADES.CBTIPODOCEMPRESA.ITEMINDEX := 0;
         END
         ELSE IF DATAMODULE1.QRYLISTAEMPRESASTIP_DOCUMENTO.TEXT = 'CE' THEN
              BEGIN
              FRMINCAPACIDADES.CBTIPODOCEMPRESA.ITEMINDEX := 2;
              END
              ELSE IF DATAMODULE1.QRYLISTAEMPRESASTIP_DOCUMENTO.TEXT = 'TI' THEN
                   BEGIN
                   FRMINCAPACIDADES.CBTIPODOCEMPRESA.ITEMINDEX := 3;
                   END;

   FRMINCAPACIDADES.EDTNUMDOCEMPRESA.TEXT := DATAMODULE1.QRYLISTAEMPRESASNUM_DOCUMENTO.TEXT;
   FRMINCAPACIDADES.EDTNOMBREEMPRESA.TEXT:= DATAMODULE1.QRYLISTAEMPRESASNOM_EMPRESA.TEXT;
   FRMEMPRESAS.FREE;
   FRMINCAPACIDADES.EDTNUMDOCEMPRESA.SetFocus;

END;

PROCEDURE TFRMEMPRESAS.DBGRID1DBLCLICK(SENDER: TOBJECT);
BEGIN
 IF GLPROCESO = 'AUTOLIQUIDACIONES' THEN
   BEGIN
   AUTOLIQUIDACIONES;
   END
   ELSE IF GLPROCESO = 'INCAPACIDADES' THEN
   BEGIN
   INCAPACIDADES;
   END
   ELSE IF GLPROCESO = 'CORRECIONES' THEN
   BEGIN
    CORRECION_AUTOLIQUIDACIONES;
   END;


END;

PROCEDURE TFRMEMPRESAS.BTNBUSCARCLICK(SENDER: TOBJECT);
BEGIN
  IF EDTBUSCAR.TEXT <> '' THEN
  BEGIN
    DATAMODULE1.DTSEMPRESAS.DATASET := DATAMODULE1.QRYLISTAEMPRESAS;
    DATAMODULE1.QRYLISTAEMPRESAS.CLOSE;
    DATAMODULE1.QRYLISTAEMPRESAS.PREPARE;
    DATAMODULE1.QRYLISTAEMPRESAS.SQL.CLEAR;
    DATAMODULE1.QRYLISTAEMPRESAS.SQL.ADD('SELECT * FROM EMPRESAS WHERE NOM_EMPRESA LIKE  :"EMPRESA" AND COD_ESTADO = :"ESTADO" ORDER BY NOM_EMPRESA');
    DATAMODULE1.QRYLISTAEMPRESAS.PARAMS[0].ASSTRING := '%' + EDTBUSCAR.TEXT + '%';
    DATAMODULE1.QRYLISTAEMPRESAS.PARAMS[1].ASSTRING := 'A';
    DATAMODULE1.QRYLISTAEMPRESAS.OPEN;
    IF  DATAMODULE1.QRYLISTAEMPRESAS.RECORDCOUNT = 0 THEN
    BEGIN
    SHOWMESSAGE('NO  HAY  EMPRESAS  CON ESTE  NOMBRE');
    END;
  END
  ELSE SHOWMESSAGE('DIGITE  LA  PALABRA  A BUSCAR');
END;

procedure TFRMEMPRESAS.CORRECION_AUTOLIQUIDACIONES;
VAR TIPO : STRING;
BEGIN
  // DATAMODULE1.QRYLISTAEMPRESAS.EDIT;
    IF DATAMODULE1.QRYLISTAEMPRESASTIP_DOCUMENTO.TEXT = 'NIT' THEN
    BEGIN
    FRMCORRECIONES.CBTIPODOCEMPRESA.ITEMINDEX := 1;
    END
    ELSE IF DATAMODULE1.QRYLISTAEMPRESASTIP_DOCUMENTO.TEXT = 'CC' THEN
         BEGIN
         FRMCORRECIONES.CBTIPODOCEMPRESA.ITEMINDEX := 0;
         END
         ELSE IF DATAMODULE1.QRYLISTAEMPRESASTIP_DOCUMENTO.TEXT = 'CE' THEN
              BEGIN
              FRMCORRECIONES.CBTIPODOCEMPRESA.ITEMINDEX := 2;
              END
              ELSE IF DATAMODULE1.QRYLISTAEMPRESASTIP_DOCUMENTO.TEXT = 'TI' THEN
                   BEGIN
                   FRMCORRECIONES.CBTIPODOCEMPRESA.ITEMINDEX := 3;
                   END;

   FRMCORRECIONES.EDNUMERO.TEXT := DATAMODULE1.QRYLISTAEMPRESASNUM_DOCUMENTO.TEXT;
   //FRMCORRECIONES.EDTSUCURSAL.TEXT:= DATAMODULE1.QRYLISTAEMPRESASCOD_SUCURSAL.TEXT;
   FRMCORRECIONES.EDTNOMBREEMPRESA.TEXT:= DATAMODULE1.QRYLISTAEMPRESASNOM_EMPRESA.TEXT;
   FRMEMPRESAS.FREE;
   FRMCORRECIONES.EDNUMERO.SetFocus;


end;

END.

