UNIT UGLOBAL;
INTERFACE
VAR
 GLUSUARIO : STRING;
 GLOFICINA : STRING;
 GLREGIONAL : STRING;
 GLNOMUSUARIO : STRING;
 GLNIVELUSUARIO : INTEGER;
 GLPORINCAPA : REAL;
 GLTIPO : STRING;
 GLNUMERO : STRING;
 GLDATE : STRING;
 GLPROCESO : STRING;
 GLSEXO : STRING;
 GLPORCOTIZACION :REAL;
 GLSALARIOMINIMO : REAL;
 GLCOTIZACION : STRING;
 GLPRESENTACION : STRING;
 GLDIA : STRING;
 GLNITEPS :STRING;
 GLEMPRESA :STRING;
 GLCREACIONEPS : STRING;

 IMPLEMENTATION


END.


