SELECT 'EPS035',AFILIADOS_COMPENSADOS.NUM_DECLARACION, INCAPACIDADES.NUM_INCAPACIDAD,
INCAPACIDADES.FEC_INICIO, INCAPACIDADES.FEC_TERMINACION, INCAPACIDADES.DIA_INCAPACIDAD,
INCAPACIDADES.SAL_BASE,SUM(DET_INCAPACIDAD.VAL_DESCONTADO),DET_INCAPACIDAD.FEC_PAGO_INCAP,
AFILIADOS_COMPENSADOS.NUM_PLANILLA 
FROM AFILIADOS_COMPENSADOS, DECLARACIONES,INCAPACIDADES, DET_INCAPACIDAD
WHERE FECHA_DECLARACION >= '01/06/2002' AND FECHA_DECLARACION <= '31/12/2002'
AND TIP_DEDUCCION = 'INC'
AND AFILIADOS_COMPENSADOS.NUM_DECLARACION = DECLARACIONES.NUM_DECLARACION
AND AFILIADOS_COMPENSADOS.AFI_NUMERO_DOC = INCAPACIDADES.AFI_NUMERO_DOC
AND INCAPACIDADES.NUM_INCAPACIDAD = DET_INCAPACIDAD.NUM_INCAPACIDAD
GROUP BY AFILIADOS_COMPENSADOS.NUM_DECLARACION, INCAPACIDADES.NUM_INCAPACIDAD,
INCAPACIDADES.FEC_INICIO, INCAPACIDADES.FEC_TERMINACION, INCAPACIDADES.DIA_INCAPACIDAD,
INCAPACIDADES.SAL_BASE,DET_INCAPACIDAD.FEC_PAGO_INCAP,
AFILIADOS_COMPENSADOS.NUM_PLANILLA 

